baseURL = "https://gifted-curie-8ce498.netlify.app"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "MyPark&Fly24"
[markup.goldmark.renderer]
unsafe = true
[[menu.company]]
URL = "#"
name = "About Us"
weight = 3
[[menu.company]]
URL = "pricing"
name = "Pricing"
weight = 1
[[menu.company]]
URL = "#"
name = "Quick Start"
weight = 2
[[menu.main]]
URL = "faq"
name = "FAQ"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 1
[[menu.product]]
URL = "pricing"
name = "Pricing"
weight = 3
[[menu.product]]
URL = "#"
name = "Features"
weight = 1
[[menu.product]]
URL = "#"
name = "Platform"
weight = 2
[[menu.support]]
URL = "faq"
name = "FAQ"
weight = 2
[[menu.support]]
URL = "terms-conditions"
name = "Terms & Conditions"
weight = 3
[[menu.support]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 4
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"
description = "This is meta description"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
logo = "images/mpf24-logo.svg"
logo_width = "200px"
[params.navigation_button]
enable = true
label = "Jetzt Buchen"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-skype"
link = "#"
title = "skype"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
